"""Add memory system tables

Revision ID: 002
Revises: 001
Create Date: 2026-02-21 14:30:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建用户长期记忆表
    op.create_table(
        "user_long_term_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("memory_type", sa.String(length=50), nullable=False),
        sa.Column("memory_key", sa.String(length=200), nullable=False),
        sa.Column("memory_value", sa.Text(), nullable=False),  # SQLite兼容：使用Text存储JSON
        sa.Column("importance_score", sa.Float(), nullable=True, server_default="1.0"),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "memory_type", "memory_key", name="uq_user_memory_type_key"
        ),
    )
    op.create_index(
        op.f("ix_user_long_term_memory_user_id"),
        "user_long_term_memory",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_long_term_memory_memory_type"),
        "user_long_term_memory",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_long_term_memory_importance_score"),
        "user_long_term_memory",
        ["importance_score"],
        unique=False,
    )

    # 2. 创建上下文摘要表
    op.create_table(
        "context_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("summary_type", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("key_insights", sa.Text(), nullable=True),  # SQLite兼容：使用Text存储JSON
        sa.Column("data_sources", sa.Text(), nullable=True),  # SQLite兼容：使用Text存储JSON
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_summaries_user_id"),
        "context_summaries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_summaries_period_start"),
        "context_summaries",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_summaries_period_end"),
        "context_summaries",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        "idx_context_summaries_user_period",
        "context_summaries",
        ["user_id", "period_start", "period_end"],
        unique=False,
    )

    # 3. 创建习惯模式表
    op.create_table(
        "habit_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("pattern_type", sa.String(length=50), nullable=False),
        sa.Column("pattern_data", sa.Text(), nullable=False),  # SQLite兼容：使用Text存储JSON
        sa.Column("confidence_score", sa.Float(), nullable=True, server_default="0.0"),
        sa.Column("first_detected", sa.Date(), nullable=False),
        sa.Column("last_observed", sa.Date(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=True, server_default="1"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["habit_id"], ["habits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_habit_patterns_user_id"),
        "habit_patterns",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_habit_patterns_habit_id"),
        "habit_patterns",
        ["habit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_habit_patterns_confidence_score"),
        "habit_patterns",
        ["confidence_score"],
        unique=False,
    )
    op.create_index(
        "idx_habit_patterns_user_habit",
        "habit_patterns",
        ["user_id", "habit_id"],
        unique=False,
    )

    # 4. 创建数据关联表
    op.create_table(
        "data_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("association_type", sa.String(length=50), nullable=False),
        sa.Column("strength", sa.Float(), nullable=True, server_default="0.0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_associations_user_id"),
        "data_associations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_source_type"),
        "data_associations",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_target_type"),
        "data_associations",
        ["target_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_strength"),
        "data_associations",
        ["strength"],
        unique=False,
    )
    op.create_index(
        "idx_data_associations_user_source",
        "data_associations",
        ["user_id", "source_type", "source_id"],
        unique=False,
    )

    # 5. 扩展现有表 - 健康记录表
    op.add_column(
        "health_records",
        sa.Column(
            "processed_for_memory", sa.Boolean(), nullable=True, server_default="false"
        ),
    )
    op.add_column(
        "health_records",
        sa.Column(
            "memory_extracted", sa.Text(), nullable=True
        ),  # SQLite兼容：使用Text存储JSON
    )

    # 6. 扩展现有表 - 习惯完成表
    op.add_column(
        "habit_completions",
        sa.Column("context_notes", sa.Text(), nullable=True),
    )
    op.add_column(
        "habit_completions",
        sa.Column(
            "memory_relevance_score", sa.Float(), nullable=True, server_default="0.0"
        ),
    )

    # 7. 扩展现有表 - 对话表
    op.add_column(
        "conversations",
        sa.Column(
            "context_summary_updated",
            sa.Boolean(),
            nullable=True,
            server_default="false",
        ),
    )
    op.add_column(
        "conversations",
        sa.Column("key_topics", sa.Text(), nullable=True),  # SQLite兼容：使用Text存储JSON
    )

    # 8. 创建额外的索引优化查询性能
    op.create_index(
        "idx_user_memory_type_key",
        "user_long_term_memory",
        ["memory_type", "memory_key"],
        unique=False,
    )
    op.create_index(
        "idx_context_summaries_type",
        "context_summaries",
        ["summary_type"],
        unique=False,
    )
    op.create_index(
        "idx_habit_patterns_type",
        "habit_patterns",
        ["pattern_type"],
        unique=False,
    )
    op.create_index(
        "idx_data_associations_association_type",
        "data_associations",
        ["association_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除额外索引
    op.drop_index(
        "idx_data_associations_association_type", table_name="data_associations"
    )
    op.drop_index("idx_habit_patterns_type", table_name="habit_patterns")
    op.drop_index("idx_context_summaries_type", table_name="context_summaries")
    op.drop_index("idx_user_memory_type_key", table_name="user_long_term_memory")

    # 删除扩展字段
    op.drop_column("conversations", "key_topics")
    op.drop_column("conversations", "context_summary_updated")
    op.drop_column("habit_completions", "memory_relevance_score")
    op.drop_column("habit_completions", "context_notes")
    op.drop_column("health_records", "memory_extracted")
    op.drop_column("health_records", "processed_for_memory")

    # 删除表
    op.drop_index("idx_data_associations_user_source", table_name="data_associations")
    op.drop_index(op.f("ix_data_associations_strength"), table_name="data_associations")
    op.drop_index(
        op.f("ix_data_associations_target_type"), table_name="data_associations"
    )
    op.drop_index(
        op.f("ix_data_associations_source_type"), table_name="data_associations"
    )
    op.drop_index(op.f("ix_data_associations_user_id"), table_name="data_associations")
    op.drop_table("data_associations")

    op.drop_index("idx_habit_patterns_user_habit", table_name="habit_patterns")
    op.drop_index(
        op.f("ix_habit_patterns_confidence_score"), table_name="habit_patterns"
    )
    op.drop_index(op.f("ix_habit_patterns_habit_id"), table_name="habit_patterns")
    op.drop_index(op.f("ix_habit_patterns_user_id"), table_name="habit_patterns")
    op.drop_table("habit_patterns")

    op.drop_index("idx_context_summaries_user_period", table_name="context_summaries")
    op.drop_index(
        op.f("ix_context_summaries_period_end"), table_name="context_summaries"
    )
    op.drop_index(
        op.f("ix_context_summaries_period_start"), table_name="context_summaries"
    )
    op.drop_index(op.f("ix_context_summaries_user_id"), table_name="context_summaries")
    op.drop_table("context_summaries")

    op.drop_index(
        op.f("ix_user_long_term_memory_importance_score"),
        table_name="user_long_term_memory",
    )
    op.drop_index(
        op.f("ix_user_long_term_memory_memory_type"), table_name="user_long_term_memory"
    )
    op.drop_index(
        op.f("ix_user_long_term_memory_user_id"), table_name="user_long_term_memory"
    )
    op.drop_table("user_long_term_memory")
    # ### end Alembic commands ###
