"""sync table schemas to migration history

Revision ID: 521bbf2caeb5
Revises: 04d894fc8aee
Create Date: 2026-02-26 13:01:17.403662

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "521bbf2caeb5"
down_revision = "04d894fc8aee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rewards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("cost_points", sa.Integer(), nullable=False),
        sa.Column("inventory_quantity", sa.Integer(), nullable=True),
        sa.Column("min_points_threshold", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_on_sale", sa.Boolean(), nullable=True),
        sa.Column("sale_discount", sa.Float(), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rewards_id"), "rewards", ["id"], unique=False)
    op.create_index(op.f("ix_rewards_name"), "rewards", ["name"], unique=False)
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.String(length=100), nullable=False),
        sa.Column("achievement_name", sa.String(length=200), nullable=False),
        sa.Column("achievement_description", sa.Text(), nullable=True),
        sa.Column("achievement_category", sa.String(length=100), nullable=True),
        sa.Column("target_value", sa.Integer(), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=True),
        sa.Column("progress_percentage", sa.Float(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("points_reward", sa.Integer(), nullable=True),
        sa.Column("badge_reward", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_achievements_id"), "achievements", ["id"], unique=False)
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.String(length=100), nullable=False),
        sa.Column("challenge_name", sa.String(length=200), nullable=False),
        sa.Column("challenge_description", sa.Text(), nullable=True),
        sa.Column("challenge_type", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("target_metric", sa.String(length=100), nullable=True),
        sa.Column("target_value", sa.Integer(), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("points_reward", sa.Integer(), nullable=True),
        sa.Column("badge_reward", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_challenges_id"), "challenges", ["id"], unique=False)
    op.create_table(
        "emotional_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "emotion_type",
            sa.Enum(
                "HAPPY",
                "SAD",
                "ANXIOUS",
                "STRESSED",
                "MOTIVATED",
                "TIRED",
                "FRUSTRATED",
                "PEACEFUL",
                "NEUTRAL",
                name="emotiontype",
            ),
            nullable=False,
        ),
        sa.Column("intensity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("trigger", sa.String(length=500), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emotional_states_id"), "emotional_states", ["id"], unique=False
    )
    op.create_table(
        "emotional_supports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "support_type",
            sa.Enum(
                "ENCOURAGEMENT",
                "VALIDATION",
                "PROBLEM_SOLVING",
                "MINDFULNESS",
                "GRATITUDE",
                "PERSPECTIVE_SHIFT",
                "SELF_COMPASSION",
                name="supporttype",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("suggested_action", sa.Text(), nullable=True),
        sa.Column("resources", sa.Text(), nullable=True),
        sa.Column("helpfulness_rating", sa.Integer(), nullable=True),
        sa.Column("emotional_impact", sa.Integer(), nullable=True),
        sa.Column("provided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emotional_supports_id"), "emotional_supports", ["id"], unique=False
    )
    op.create_table(
        "food_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=True),
        sa.Column("serving_size", sa.Float(), nullable=False),
        sa.Column("serving_unit", sa.String(length=50), nullable=False),
        sa.Column("calories_per_serving", sa.Float(), nullable=False),
        sa.Column("protein_per_serving", sa.Integer(), nullable=True),
        sa.Column("carbs_per_serving", sa.Integer(), nullable=True),
        sa.Column("fat_per_serving", sa.Integer(), nullable=True),
        sa.Column("fiber_per_serving", sa.Integer(), nullable=True),
        sa.Column("sugar_per_serving", sa.Integer(), nullable=True),
        sa.Column("sodium_per_serving", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("calories_per_100g", sa.Float(), nullable=True),
        sa.Column("protein_per_100g", sa.Float(), nullable=True),
        sa.Column("carbs_per_100g", sa.Float(), nullable=True),
        sa.Column("fat_per_100g", sa.Float(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_food_items_id"), "food_items", ["id"], unique=False)
    op.create_table(
        "gratitude_journals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("entry", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("intensity", sa.Integer(), nullable=True),
        sa.Column("mood_before", sa.Integer(), nullable=True),
        sa.Column("mood_after", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gratitude_journals_id"), "gratitude_journals", ["id"], unique=False
    )
    op.create_table(
        "leaderboard_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("leaderboard_type", sa.String(length=100), nullable=False),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("previous_rank", sa.Integer(), nullable=True),
        sa.Column("rank_change", sa.Integer(), nullable=True),
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leaderboard_entries_id"), "leaderboard_entries", ["id"], unique=False
    )
    op.create_table(
        "mindfulness_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_type", sa.String(length=100), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("focus_area", sa.String(length=200), nullable=True),
        sa.Column("difficulty_level", sa.Integer(), nullable=True),
        sa.Column("relaxation_level", sa.Integer(), nullable=True),
        sa.Column("focus_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mindfulness_exercises_id"),
        "mindfulness_exercises",
        ["id"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"),
        "password_reset_tokens",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=True,
    )
    op.create_table(
        "points_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("points_amount", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.String(length=100), nullable=True),
        sa.Column("reference_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_points_transactions_id"), "points_transactions", ["id"], unique=False
    )
    op.create_table(
        "positive_affirmations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("affirmation", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("personalized", sa.Boolean(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effectiveness", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_positive_affirmations_id"),
        "positive_affirmations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "reward_redemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reward_id", sa.Integer(), nullable=False),
        sa.Column("redemption_point_cost", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("recipient_name", sa.String(length=100), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("notes_internal", sa.Text(), nullable=True),
        sa.Column("redemption_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["reward_id"], ["rewards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reward_redemptions_id"), "reward_redemptions", ["id"], unique=False
    )
    op.create_table(
        "streak_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("streak_type", sa.String(length=100), nullable=False),
        sa.Column("streak_name", sa.String(length=200), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=True),
        sa.Column("longest_streak", sa.Integer(), nullable=True),
        sa.Column("streak_start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("milestones_reached", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_streak_records_id"), "streak_records", ["id"], unique=False
    )
    op.create_table(
        "stress_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stress_level", sa.Integer(), nullable=False),
        sa.Column("physical_symptoms", sa.Text(), nullable=True),
        sa.Column("emotional_symptoms", sa.Text(), nullable=True),
        sa.Column("cognitive_symptoms", sa.Text(), nullable=True),
        sa.Column("stressors", sa.Text(), nullable=True),
        sa.Column("coping_strategies", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stress_levels_id"), "stress_levels", ["id"], unique=False)
    op.create_table(
        "user_badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("badge_id", sa.String(length=100), nullable=False),
        sa.Column("badge_name", sa.String(length=200), nullable=False),
        sa.Column("badge_description", sa.Text(), nullable=True),
        sa.Column(
            "badge_category",
            sa.Enum(
                "WEIGHT_LOSS",
                "HABIT_MASTERY",
                "NUTRITION",
                "EMOTIONAL_WELLNESS",
                "CONSISTENCY",
                "MILESTONE",
                "SOCIAL",
                "SPECIAL",
                name="badgecategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "badge_level",
            sa.Enum(
                "BRONZE", "SILVER", "GOLD", "PLATINUM", "DIAMOND", name="badgelevel"
            ),
            nullable=False,
        ),
        sa.Column("badge_icon", sa.String(length=500), nullable=True),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("earned_criteria", sa.Text(), nullable=True),
        sa.Column("progress_data", sa.JSON(), nullable=True),
        sa.Column("is_showcased", sa.Boolean(), nullable=True),
        sa.Column("showcase_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_badges_id"), "user_badges", ["id"], unique=False)
    op.create_table(
        "user_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("current_level", sa.Integer(), nullable=True),
        sa.Column("current_title", sa.String(length=100), nullable=True),
        sa.Column("experience_points", sa.Integer(), nullable=True),
        sa.Column("points_to_next_level", sa.Integer(), nullable=True),
        sa.Column("level_up_count", sa.Integer(), nullable=True),
        sa.Column("last_level_up", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_levels_id"), "user_levels", ["id"], unique=False)
    op.create_table(
        "user_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column("current_points", sa.Integer(), nullable=True),
        sa.Column("lifetime_points", sa.Integer(), nullable=True),
        sa.Column("nutrition_points", sa.Integer(), nullable=True),
        sa.Column("habit_points", sa.Integer(), nullable=True),
        sa.Column("emotional_points", sa.Integer(), nullable=True),
        sa.Column("login_points", sa.Integer(), nullable=True),
        sa.Column("achievement_points", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_points_id"), "user_points", ["id"], unique=False)
    op.create_table(
        "water_intakes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_ml", sa.Integer(), nullable=False),
        sa.Column("intake_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_water_intakes_id"), "water_intakes", ["id"], unique=False)
    op.alter_column(
        "calorie_goals", "target_calories", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "calorie_goals",
        "target_protein",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "calorie_goals",
        "target_carbs",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "calorie_goals",
        "target_fat",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_calorie_goals_user_date"), table_name="calorie_goals")
    op.create_index(
        op.f("ix_calorie_goals_goal_date"), "calorie_goals", ["goal_date"], unique=False
    )
    op.create_index(op.f("ix_calorie_goals_id"), "calorie_goals", ["id"], unique=False)
    op.create_index(
        op.f("ix_calorie_goals_user_id"), "calorie_goals", ["user_id"], unique=False
    )
    op.drop_index(op.f("idx_context_summaries_type"), table_name="context_summaries")
    op.drop_index(
        op.f("idx_context_summaries_user_period"), table_name="context_summaries"
    )
    op.drop_index(
        op.f("ix_context_summaries_period_end"), table_name="context_summaries"
    )
    op.drop_index(
        op.f("ix_context_summaries_period_start"), table_name="context_summaries"
    )
    op.drop_index(op.f("ix_context_summaries_user_id"), table_name="context_summaries")
    op.create_index(
        op.f("ix_context_summaries_id"), "context_summaries", ["id"], unique=False
    )
    op.drop_column("conversations", "key_topics")
    op.drop_column("conversations", "context_summary_updated")
    op.drop_index(
        op.f("idx_data_associations_association_type"), table_name="data_associations"
    )
    op.drop_index(
        op.f("idx_data_associations_user_source"), table_name="data_associations"
    )
    op.drop_index(
        op.f("ix_data_associations_source_type"), table_name="data_associations"
    )
    op.drop_index(op.f("ix_data_associations_strength"), table_name="data_associations")
    op.drop_index(
        op.f("ix_data_associations_target_type"), table_name="data_associations"
    )
    op.drop_index(op.f("ix_data_associations_user_id"), table_name="data_associations")
    op.create_index(
        op.f("ix_data_associations_id"), "data_associations", ["id"], unique=False
    )
    op.alter_column(
        "event_logs",
        "event_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.create_index(
        "idx_event_logs_notification",
        "event_logs",
        ["notification_status", "occurred_at"],
        unique=False,
    )
    op.alter_column(
        "exercise_checkins",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "exercise_checkins",
        "intensity",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "exercise_checkins",
        "distance_km",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "calories_burned",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "exercise_checkins",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "exercise_checkins",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "exercise_checkins",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_exercise_checkins_deleted_at"), table_name="exercise_checkins"
    )
    op.drop_index(
        op.f("idx_exercise_checkins_started_at"), table_name="exercise_checkins"
    )
    op.drop_index(op.f("idx_exercise_checkins_user_id"), table_name="exercise_checkins")
    op.create_index(
        op.f("ix_exercise_checkins_id"), "exercise_checkins", ["id"], unique=False
    )
    op.drop_column("habit_completions", "memory_relevance_score")
    op.drop_column("habit_completions", "context_notes")
    op.drop_index(op.f("ix_habit_goals_habit_id"), table_name="habit_goals")
    op.drop_index(op.f("ix_habit_goals_is_active"), table_name="habit_goals")
    op.drop_index(op.f("ix_habit_goals_user_id"), table_name="habit_goals")
    op.create_index(op.f("ix_habit_goals_id"), "habit_goals", ["id"], unique=False)
    op.drop_index(op.f("idx_habit_patterns_type"), table_name="habit_patterns")
    op.drop_index(op.f("idx_habit_patterns_user_habit"), table_name="habit_patterns")
    op.drop_index(
        op.f("ix_habit_patterns_confidence_score"), table_name="habit_patterns"
    )
    op.drop_index(op.f("ix_habit_patterns_habit_id"), table_name="habit_patterns")
    op.drop_index(op.f("ix_habit_patterns_user_id"), table_name="habit_patterns")
    op.create_index(
        op.f("ix_habit_patterns_id"), "habit_patterns", ["id"], unique=False
    )
    op.alter_column(
        "habits",
        "category",
        existing_type=postgresql.ENUM(
            "DIET",
            "EXERCISE",
            "SLEEP",
            "MENTAL_HEALTH",
            "HYDRATION",
            "OTHER",
            name="habitcategory",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "habits",
        "frequency",
        existing_type=postgresql.ENUM(
            "DAILY", "WEEKLY", "MONTHLY", name="habitfrequency"
        ),
        type_=sa.String(length=50),
        nullable=False,
    )
    op.alter_column(
        "health_assessments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_health_assessments_id"), "health_assessments", ["id"], unique=False
    )
    op.drop_column("health_records", "processed_for_memory")
    op.drop_column("health_records", "memory_extracted")
    op.alter_column(
        "meal_items",
        "serving_size",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "quantity",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "meal_items",
        "calories_per_serving",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "protein_per_serving",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "carbs_per_serving",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "fat_per_serving",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_meal_items_food_item_id"), table_name="meal_items")
    op.drop_index(op.f("idx_meal_items_meal_id"), table_name="meal_items")
    op.create_index(op.f("ix_meal_items_id"), "meal_items", ["id"], unique=False)
    op.create_foreign_key(None, "meal_items", "food_items", ["food_item_id"], ["id"])
    op.alter_column(
        "meals", "name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "meals",
        "protein",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "carbs",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "fat",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "fiber",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "sugar",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "sodium",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_meals_meal_datetime"), table_name="meals")
    op.drop_index(op.f("idx_meals_user_id"), table_name="meals")
    op.create_index(op.f("ix_meals_id"), "meals", ["id"], unique=False)
    op.drop_index(op.f("idx_memory_index_log_status"), table_name="memory_index_log")
    op.drop_index(op.f("idx_memory_index_log_user_id"), table_name="memory_index_log")
    op.create_index(
        op.f("ix_memory_index_log_status"), "memory_index_log", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_memory_index_log_user_id"),
        "memory_index_log",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "notification_templates",
        "variables",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column("notifications", sa.Column("metadata", sa.JSON(), nullable=True))
    op.alter_column(
        "notifications",
        "template_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_notifications_user_created"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_status"), table_name="notifications")
    op.create_index(
        "idx_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_notifications_user_status",
        "notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.drop_column("notifications", "metadata_")
    op.alter_column(
        "unified_memory",
        "content_keywords",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("idx_unified_memory_created_at"), table_name="unified_memory")
    op.drop_index(op.f("idx_unified_memory_memory_type"), table_name="unified_memory")
    op.drop_index(op.f("idx_unified_memory_source_type"), table_name="unified_memory")
    op.drop_index(op.f("idx_unified_memory_user_id"), table_name="unified_memory")
    op.create_index(
        op.f("ix_unified_memory_created_at"),
        "unified_memory",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unified_memory_is_active"),
        "unified_memory",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unified_memory_is_indexed"),
        "unified_memory",
        ["is_indexed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unified_memory_memory_type"),
        "unified_memory",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unified_memory_source_type"),
        "unified_memory",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unified_memory_user_id"), "unified_memory", ["user_id"], unique=False
    )
    op.drop_index(op.f("idx_user_memory_type_key"), table_name="user_long_term_memory")
    op.drop_index(
        op.f("ix_user_long_term_memory_importance_score"),
        table_name="user_long_term_memory",
    )
    op.drop_index(
        op.f("ix_user_long_term_memory_memory_type"), table_name="user_long_term_memory"
    )
    op.drop_index(
        op.f("ix_user_long_term_memory_user_id"), table_name="user_long_term_memory"
    )
    op.drop_constraint(
        op.f("uq_user_memory_type_key"), "user_long_term_memory", type_="unique"
    )
    op.create_index(
        op.f("ix_user_long_term_memory_id"),
        "user_long_term_memory",
        ["id"],
        unique=False,
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_index(
        op.f("ix_user_long_term_memory_id"), table_name="user_long_term_memory"
    )
    op.create_unique_constraint(
        op.f("uq_user_memory_type_key"),
        "user_long_term_memory",
        ["user_id", "memory_type", "memory_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_user_long_term_memory_user_id"),
        "user_long_term_memory",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_long_term_memory_memory_type"),
        "user_long_term_memory",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_long_term_memory_importance_score"),
        "user_long_term_memory",
        ["importance_score"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_memory_type_key"),
        "user_long_term_memory",
        ["memory_type", "memory_key"],
        unique=False,
    )
    op.drop_index(op.f("ix_unified_memory_user_id"), table_name="unified_memory")
    op.drop_index(op.f("ix_unified_memory_source_type"), table_name="unified_memory")
    op.drop_index(op.f("ix_unified_memory_memory_type"), table_name="unified_memory")
    op.drop_index(op.f("ix_unified_memory_is_indexed"), table_name="unified_memory")
    op.drop_index(op.f("ix_unified_memory_is_active"), table_name="unified_memory")
    op.drop_index(op.f("ix_unified_memory_created_at"), table_name="unified_memory")
    op.create_index(
        op.f("idx_unified_memory_user_id"), "unified_memory", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_unified_memory_source_type"),
        "unified_memory",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_unified_memory_memory_type"),
        "unified_memory",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_unified_memory_created_at"),
        "unified_memory",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "unified_memory",
        "content_keywords",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "metadata_",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index("idx_notifications_user_status", table_name="notifications")
    op.drop_index("idx_notifications_user_created", table_name="notifications")
    op.create_index(
        op.f("ix_notifications_user_status"),
        "notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_created"),
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.alter_column(
        "notifications",
        "template_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("notifications", "metadata")
    op.alter_column(
        "notification_templates",
        "variables",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_memory_index_log_user_id"), table_name="memory_index_log")
    op.drop_index(op.f("ix_memory_index_log_status"), table_name="memory_index_log")
    op.create_index(
        op.f("idx_memory_index_log_user_id"),
        "memory_index_log",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_memory_index_log_status"),
        "memory_index_log",
        ["status"],
        unique=False,
    )
    op.drop_index(op.f("ix_meals_id"), table_name="meals")
    op.create_index(op.f("idx_meals_user_id"), "meals", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_meals_meal_datetime"), "meals", ["meal_datetime"], unique=False
    )
    op.alter_column(
        "meals",
        "sodium",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "sugar",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "fiber",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "fat",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "carbs",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals",
        "protein",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meals", "name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.drop_constraint(None, "meal_items", type_="foreignkey")
    op.drop_index(op.f("ix_meal_items_id"), table_name="meal_items")
    op.create_index(
        op.f("idx_meal_items_meal_id"), "meal_items", ["meal_id"], unique=False
    )
    op.create_index(
        op.f("idx_meal_items_food_item_id"),
        "meal_items",
        ["food_item_id"],
        unique=False,
    )
    op.alter_column(
        "meal_items",
        "fat_per_serving",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "carbs_per_serving",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "protein_per_serving",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "calories_per_serving",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_items",
        "quantity",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "meal_items",
        "serving_size",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.add_column(
        "health_records",
        sa.Column("memory_extracted", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "health_records",
        sa.Column(
            "processed_for_memory",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_health_assessments_id"), table_name="health_assessments")
    op.alter_column(
        "health_assessments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "habits",
        "frequency",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM("DAILY", "WEEKLY", "MONTHLY", name="habitfrequency"),
        nullable=True,
    )
    op.alter_column(
        "habits",
        "category",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "DIET",
            "EXERCISE",
            "SLEEP",
            "MENTAL_HEALTH",
            "HYDRATION",
            "OTHER",
            name="habitcategory",
        ),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_habit_patterns_id"), table_name="habit_patterns")
    op.create_index(
        op.f("ix_habit_patterns_user_id"), "habit_patterns", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_habit_patterns_habit_id"), "habit_patterns", ["habit_id"], unique=False
    )
    op.create_index(
        op.f("ix_habit_patterns_confidence_score"),
        "habit_patterns",
        ["confidence_score"],
        unique=False,
    )
    op.create_index(
        op.f("idx_habit_patterns_user_habit"),
        "habit_patterns",
        ["user_id", "habit_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_habit_patterns_type"),
        "habit_patterns",
        ["pattern_type"],
        unique=False,
    )
    op.drop_index(op.f("ix_habit_goals_id"), table_name="habit_goals")
    op.create_index(
        op.f("ix_habit_goals_user_id"), "habit_goals", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_habit_goals_is_active"), "habit_goals", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_habit_goals_habit_id"), "habit_goals", ["habit_id"], unique=False
    )
    op.add_column(
        "habit_completions",
        sa.Column("context_notes", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "habit_completions",
        sa.Column(
            "memory_relevance_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_exercise_checkins_id"), table_name="exercise_checkins")
    op.create_index(
        op.f("idx_exercise_checkins_user_id"),
        "exercise_checkins",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_exercise_checkins_started_at"),
        "exercise_checkins",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_exercise_checkins_deleted_at"),
        "exercise_checkins",
        ["deleted_at"],
        unique=False,
    )
    op.alter_column(
        "exercise_checkins",
        "deleted_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "exercise_checkins",
        "started_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "exercise_checkins",
        "calories_burned",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "distance_km",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "intensity",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "exercise_checkins",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_index(
        "idx_event_logs_pending",
        table_name="event_logs",
        postgresql_where=sa.text("lower(notification_status) = 'pending'"),
    )
    op.alter_column(
        "event_logs",
        "event_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_data_associations_id"), table_name="data_associations")
    op.create_index(
        op.f("ix_data_associations_user_id"),
        "data_associations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_target_type"),
        "data_associations",
        ["target_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_strength"),
        "data_associations",
        ["strength"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_associations_source_type"),
        "data_associations",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_data_associations_user_source"),
        "data_associations",
        ["user_id", "source_type", "source_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_data_associations_association_type"),
        "data_associations",
        ["association_type"],
        unique=False,
    )
    op.add_column(
        "conversations",
        sa.Column(
            "context_summary_updated",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column("key_topics", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_context_summaries_id"), table_name="context_summaries")
    op.create_index(
        op.f("ix_context_summaries_user_id"),
        "context_summaries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_summaries_period_start"),
        "context_summaries",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_summaries_period_end"),
        "context_summaries",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("idx_context_summaries_user_period"),
        "context_summaries",
        ["user_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("idx_context_summaries_type"),
        "context_summaries",
        ["summary_type"],
        unique=False,
    )
    op.drop_index(op.f("ix_calorie_goals_user_id"), table_name="calorie_goals")
    op.drop_index(op.f("ix_calorie_goals_id"), table_name="calorie_goals")
    op.drop_index(op.f("ix_calorie_goals_goal_date"), table_name="calorie_goals")
    op.create_index(
        op.f("idx_calorie_goals_user_date"),
        "calorie_goals",
        ["user_id", "goal_date"],
        unique=False,
    )
    op.alter_column(
        "calorie_goals",
        "target_fat",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "calorie_goals",
        "target_carbs",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "calorie_goals",
        "target_protein",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "calorie_goals", "target_calories", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(op.f("ix_water_intakes_id"), table_name="water_intakes")
    op.drop_table("water_intakes")
    op.drop_index(op.f("ix_user_points_id"), table_name="user_points")
    op.drop_table("user_points")
    op.drop_index(op.f("ix_user_levels_id"), table_name="user_levels")
    op.drop_table("user_levels")
    op.drop_index(op.f("ix_user_badges_id"), table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index(op.f("ix_stress_levels_id"), table_name="stress_levels")
    op.drop_table("stress_levels")
    op.drop_index(op.f("ix_streak_records_id"), table_name="streak_records")
    op.drop_table("streak_records")
    op.drop_index(op.f("ix_reward_redemptions_id"), table_name="reward_redemptions")
    op.drop_table("reward_redemptions")
    op.drop_index(
        op.f("ix_positive_affirmations_id"), table_name="positive_affirmations"
    )
    op.drop_table("positive_affirmations")
    op.drop_index(op.f("ix_points_transactions_id"), table_name="points_transactions")
    op.drop_table("points_transactions")
    op.drop_index(
        op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(
        op.f("ix_mindfulness_exercises_id"), table_name="mindfulness_exercises"
    )
    op.drop_table("mindfulness_exercises")
    op.drop_index(op.f("ix_leaderboard_entries_id"), table_name="leaderboard_entries")
    op.drop_table("leaderboard_entries")
    op.drop_index(op.f("ix_gratitude_journals_id"), table_name="gratitude_journals")
    op.drop_table("gratitude_journals")
    op.drop_index(op.f("ix_food_items_id"), table_name="food_items")
    op.drop_table("food_items")
    op.drop_index(op.f("ix_emotional_supports_id"), table_name="emotional_supports")
    op.drop_table("emotional_supports")
    op.drop_index(op.f("ix_emotional_states_id"), table_name="emotional_states")
    op.drop_table("emotional_states")
    op.drop_index(op.f("ix_challenges_id"), table_name="challenges")
    op.drop_table("challenges")
    op.drop_index(op.f("ix_achievements_id"), table_name="achievements")
    op.drop_table("achievements")
    op.drop_index(op.f("ix_rewards_name"), table_name="rewards")
    op.drop_index(op.f("ix_rewards_id"), table_name="rewards")
    op.drop_table("rewards")
    # ### end Alembic commands ###
